### ISSUE TITLE
Crash when search fails (e.g. song not found at Genius)

### ISSUE THREAD

**Issue by airdrummingfool** [airdrummingfool/genius-lyrics#2]
Service call:
```json
{
 "api_key":"[redacted]",
 "artist_name":"EMBRZ, Leo Stannard",
 "song_title":"She Won't Let Me Down (feat. Leo Stannard)",
 "entity_id":"sensor.lyrics"
}
```

Error:
```
Sat Aug 17 2019 23:15:08 GMT-0500 (Central Daylight Time)
Error while executing automation automation.misc_update_genius_lyrics_when_spotify_song_changes. Unknown error for call_service at pos 1: 
Traceback (most recent call last):
  File "/usr/src/app/homeassistant/components/automation/__init__.py", line 427, in action
    await script_obj.async_run(variables, context)
  File "/usr/src/app/homeassistant/helpers/script.py", line 151, in async_run
    await self._handle_action(action, variables, context)
  File "/usr/src/app/homeassistant/helpers/script.py", line 235, in _handle_action
    await self._actions[_determine_action(action)](action, variables, context)
  File "/usr/src/app/homeassistant/helpers/script.py", line 318, in _async_call_service
    context=context,
  File "/usr/src/app/homeassistant/helpers/service.py", line 97, in async_call_from_config
    domain, service_name, service_data, blocking=blocking, context=context
  File "/usr/src/app/homeassistant/core.py", line 1235, in async_call
    await asyncio.shield(self._execute_service(handler, service_call))
  File "/usr/src/app/homeassistant/core.py", line 1262, in _execute_service
    await self._hass.async_add_executor_job(handler.func, service_call)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/genius_lyrics/__init__.py", line 51, in search_lyrics
    attrs = song.to_dict()
AttributeError: 'NoneType' object has no attribute 'to_dict'
```

**Comment by airdrummingfool** [comment]
Turns out this song just doesn't exist at Genius... huh.

When the song doesn't exist (or there are no search results for whatever reason), the underlying Genius library returns `None`, which we should handle less ungracefully.
